import type {
  Referral,
  ReferralTwo,
  Transaction,
  User,
  UserTwo,
  WalletTransaction,
} from "./types";

export const dummyUsers: User[] = [
  {
    id: 1,
    name: "Judith Dimokechukwu",
    email: "judithdimokechukwu@gmail.com",
    status: "Active",
    kycStatus: "Approved",
    country: "Australia",
    lastTransaction: "2025-05-27 19:25",
  },
  {
    id: 2,
    name: "Johnathan Peterson",
    email: "jpeters@example.com",
    status: "Active",
    kycStatus: "Approved",
    country: "Canada",
    lastTransaction: "2025-05-26 11:45",
  },
  {
    id: 3,
    name: "Maria Garcia",
    email: "mariag@example.com",
    status: "Flagged",
    kycStatus: "Approved",
    country: "Spain",
    lastTransaction: "2025-05-25 08:10",
  },
  {
    id: 4,
    name: "Chen Wei",
    email: "chen.wei@example.com",
    status: "Active",
    kycStatus: "Pending",
    country: "China",
    lastTransaction: "2025-05-27 14:00",
  },
  {
    id: 5,
    name: "Fatima Al-Sayed",
    email: "fatima.a@example.com",
    status: "Suspended",
    kycStatus: "Approved",
    country: "Egypt",
    lastTransaction: "2025-04-12 21:30",
  },
  {
    id: 6,
    name: "David Smith",
    email: "d.smith@example.co.uk",
    status: "Active",
    kycStatus: "Pending",
    country: "United Kingdom",
    lastTransaction: "2025-05-27 09:05",
  },
  {
    id: 7,
    name: "Yuki Tanaka",
    email: "yuki.t@example.jp",
    status: "Active",
    kycStatus: "Rejected",
    country: "Japan",
    lastTransaction: "2025-05-19 18:55",
  },
  {
    id: 8,
    name: "Adebayo Adekunle",
    email: "adebayo.a@example.ng",
    status: "Flagged",
    kycStatus: "Approved",
    country: "Nigeria",
    lastTransaction: "2025-05-24 12:00",
  },
  {
    id: 9,
    name: "Isabella Rossi",
    email: "isabella.r@example.it",
    status: "Active",
    kycStatus: "Rejected",
    country: "Italy",
    lastTransaction: "2025-05-21 16:20",
  },
  {
    id: 10,
    name: "Liam O'Sullivan",
    email: "liam.os@example.ie",
    status: "Active",
    kycStatus: "Approved",
    country: "Ireland",
    lastTransaction: "2025-05-27 19:35",
  },
];

export const transactions: Transaction[] = [
  {
    id: "txn_1",
    customer: "Judith Dimokechukwu",
    amount: 100,
    title: "Money Transfer",
    recipient: "Franklin",
    status: "Initiated",
    paymentMethod: "Bank Transfer",
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "txn_2",
    customer: "Judith Dimokechukwu",
    amount: 10,
    title: "Electricity",
    recipient: "EEDC",
    status: "Completed",
    paymentMethod: "PAY ID",
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "txn_3",
    customer: "Judith Dimokechukwu",
    amount: 5,
    title: "Airtime",
    recipient: "8147309693",
    status: "Completed",
    paymentMethod: "Wallet",
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "txn_4",
    customer: "Judith Dimokechukwu",
    amount: 5,
    title: "Airtime",
    recipient: "8147309693",
    status: "Completed",
    paymentMethod: "PAY ID",
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "txn_5",
    customer: "Judith Dimokechukwu",
    amount: 5,
    title: "Airtime",
    recipient: "8147309693",
    status: "Completed",
    paymentMethod: "Wallet",
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "txn_6",
    customer: "Judith Dimokechukwu",
    amount: 500,
    title: "Money Transfer",
    recipient: "Judith",
    status: "Completed",
    paymentMethod: "Bank Transfer",
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "txn_7",
    customer: "Judith Dimokechukwu",
    amount: 5,
    title: "Airtime",
    recipient: "8147309693",
    status: "Completed",
    paymentMethod: "Bank Transfer",
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "txn_8",
    customer: "Judith Dimokechukwu",
    amount: 5,
    title: "Airtime",
    recipient: "AUD",
    status: "Completed",
    paymentMethod: "Bank Transfer",
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "txn_9",
    customer: "Judith Dimokechukwu",
    amount: 500,
    title: "Money Transfer",
    recipient: "Abimbola",
    status: "Completed",
    paymentMethod: "Wallet",
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "txn_10",
    customer: "Judith Dimokechukwu",
    amount: 5,
    title: "Airtime",
    recipient: "8147309693",
    status: "Completed",
    paymentMethod: "Bank Transfer",
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "txn_11",
    customer: "Judith Dimokechukwu",
    amount: 5,
    title: "Airtime",
    recipient: "8147309693",
    status: "Completed",
    paymentMethod: "Bank Transfer",
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "txn_12",
    customer: "Judith Dimokechukwu",
    amount: 500,
    title: "Money Transfer",
    recipient: "Abimbola",
    status: "Completed",
    paymentMethod: "Bank Transfer",
    dateCreated: "2025-05-27 19:25pm",
  },
];

export const referrals: Referral[] = [
  {
    id: "ref_1",
    name: "Franklin Okhabue",
    email: "franklinokhabue@gmail.com",
    codeUsed: "REF12345",
    reward: 5,
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "ref_2",
    name: "Franklin Okhabue",
    email: "franklinokhabue@gmail.com",
    codeUsed: "REF12345",
    reward: 5,
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    id: "ref_3",
    name: "Franklin Okhabue",
    email: "franklinokhabue@gmail.com",
    codeUsed: "REF12345",
    reward: 5,
    dateCreated: "2025-05-27 19:25pm",
  },
];

export const walletTransactions: WalletTransaction[] = [
  {
    transactionId: "12345678",
    title: "Airtime (MTN)",
    type: "Withdrawal",
    recipient: "8147309693",
    amount: 5,
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    transactionId: "12345678",
    title: "Fund Wallet",
    type: "Funding",
    recipient: "Judith",
    amount: 100,
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    transactionId: "12345678",
    title: "Airtime (MTN)",
    type: "Withdrawal",
    recipient: "8147309693",
    amount: 5,
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    transactionId: "12345678",
    title: "Airtime (MTN)",
    type: "Withdrawal",
    recipient: "8147309693",
    amount: 5,
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    transactionId: "12345678",
    title: "Fund Wallet",
    type: "Funding",
    recipient: "Judith",
    amount: 100,
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    transactionId: "12345678",
    title: "Airtime (MTN)",
    type: "Withdrawal",
    recipient: "8147309693",
    amount: 5,
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    transactionId: "12345678",
    title: "Airtime (MTN)",
    type: "Withdrawal",
    recipient: "8147309693",
    amount: 5,
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    transactionId: "12345678",
    title: "Fund Wallet",
    type: "Funding",
    recipient: "Judith",
    amount: 100,
    dateCreated: "2025-05-27 19:25pm",
  },
  {
    transactionId: "12345678",
    title: "Airtime (MTN)",
    type: "Withdrawal",
    recipient: "8147309693",
    amount: 5,
    dateCreated: "2025-05-27 19:25pm",
  },
];

export const referralsTwo: ReferralTwo[] = [
  {
    id: 1,
    referrer: "Judith Dimokechukwu",
    referralCode: "REF1234",
    referredUser: "Francis Ola",
    dateJoined: "2025-05-27 19:25pm",
    bonusStatus: "Pending",
    bonusAmount: "$10 AUD",
  },
  {
    id: 2,
    referrer: "Judith Dimokechukwu",
    referralCode: "REF1234",
    referredUser: "Francis Ola",
    dateJoined: "2025-05-27 19:25pm",
    bonusStatus: "Pending",
    bonusAmount: "$10 AUD",
  },
  {
    id: 3,
    referrer: "Judith Dimokechukwu",
    referralCode: "REF1234",
    referredUser: "Francis Ola",
    dateJoined: "2025-05-27 19:25pm",
    bonusStatus: "Pending",
    bonusAmount: "$10 AUD",
  },
  {
    id: 4,
    referrer: "Samuel Okafor",
    referralCode: "REF5678",
    referredUser: "Angela Kalu",
    dateJoined: "2025-06-01 14:00pm",
    bonusStatus: "Completed",
    bonusAmount: "$20 AUD",
  },
  {
    id: 5,
    referrer: "Samuel Okafor",
    referralCode: "REF5678",
    referredUser: "Angela Kalu",
    dateJoined: "2025-06-01 14:00pm",
    bonusStatus: "Completed",
    bonusAmount: "$20 AUD",
  },
  {
    id: 6,
    referrer: "Samuel Okafor",
    referralCode: "REF5678",
    referredUser: "Angela Kalu",
    dateJoined: "2025-06-01 14:00pm",
    bonusStatus: "Completed",
    bonusAmount: "$20 AUD",
  },
  {
    id: 7,
    referrer: "Linda Adebayo",
    referralCode: "REF9101",
    referredUser: "Chike Nwosu",
    dateJoined: "2025-06-10 11:30am",
    bonusStatus: "Completed",
    bonusAmount: "$15 AUD",
  },
  {
    id: 8,
    referrer: "Linda Adebayo",
    referralCode: "REF9101",
    referredUser: "Chike Nwosu",
    dateJoined: "2025-06-10 11:30am",
    bonusStatus: "Completed",
    bonusAmount: "$15 AUD",
  },
  {
    id: 9,
    referrer: "Linda Adebayo",
    referralCode: "REF9101",
    referredUser: "Chike Nwosu",
    dateJoined: "2025-06-10 11:30am",
    bonusStatus: "Completed",
    bonusAmount: "$15 AUD",
  },
  {
    id: 10,
    referrer: "Samuel Okafor",
    referralCode: "REF5678",
    referredUser: "Angela Kalu",
    dateJoined: "2025-06-01 14:00pm",
    bonusStatus: "Completed",
    bonusAmount: "$20 AUD",
  },
  {
    id: 11,
    referrer: "Samuel Okafor",
    referralCode: "REF5678",
    referredUser: "Angela Kalu",
    dateJoined: "2025-06-01 14:00pm",
    bonusStatus: "Completed",
    bonusAmount: "$20 AUD",
  },
  {
    id: 12,
    referrer: "Samuel Okafor",
    referralCode: "REF5678",
    referredUser: "Angela Kalu",
    dateJoined: "2025-06-01 14:00pm",
    bonusStatus: "Completed",
    bonusAmount: "$20 AUD",
  },
];

export const users: UserTwo[] = [
  {
    id: 1,
    email: "judithdimokechukwu@gmail.com",
    firstName: "Judith",
    lastName: "Dimokechukwu",
    gender: "Female",
    status: "Approved",
  },
  {
    id: 2,
    email: "desmondobiora@gmail.com",
    firstName: "Desmond",
    lastName: "Obiora",
    gender: "Male",
    status: "Approved",
  },
  {
    id: 3,
    email: "judithdimokechukwu@gmail.com",
    firstName: "Judith",
    lastName: "Dimokechukwu",
    gender: "Female",
    status: "Approved",
  },
  {
    id: 4,
    email: "franklinchukwu@gmail.com",
    firstName: "Franklin",
    lastName: "Chukwu",
    gender: "Male",
    status: "Approved",
  },
  {
    id: 5,
    email: "desmondobiora@gmail.com",
    firstName: "Desmond",
    lastName: "Obiora",
    gender: "Male",
    status: "Approved",
  },
  {
    id: 6,
    email: "ayoolaawoniyi@gmail.com",
    firstName: "Ayoola",
    lastName: "Awoniyi",
    gender: "Female",
    status: "Approved",
  },
  {
    id: 7,
    email: "judithdimokechukwu@gmail.com",
    firstName: "Judith",
    lastName: "Dimokechukwu",
    gender: "Female",
    status: "Approved",
  },
  {
    id: 8,
    email: "ayoolaawoniyi@gmail.com",
    firstName: "Ayoola",
    lastName: "Awoniyi",
    gender: "Female",
    status: "Approved",
  },
  {
    id: 9,
    email: "judithdimokechukwu@gmail.com",
    firstName: "Judith",
    lastName: "Dimokechukwu",
    gender: "Female",
    status: "Approved",
  },
  {
    id: 10,
    email: "judithdimokechukwu@gmail.com",
    firstName: "Judith",
    lastName: "Dimokechukwu",
    gender: "Female",
    status: "Approved",
  },
  {
    id: 11,
    email: "desmondobiora@gmail.com",
    firstName: "Desmond",
    lastName: "Obiora",
    gender: "Male",
    status: "Approved",
  },
  {
    id: 12,
    email: "judithdimokechukwu@gmail.com",
    firstName: "Judith",
    lastName: "Dimokechukwu",
    gender: "Female",
    status: "Approved",
  },
  {
    id: 13,
    email: "franklinchukwu@gmail.com",
    firstName: "Franklin",
    lastName: "Chukwu",
    gender: "Male",
    status: "Approved",
  },
  {
    id: 14,
    email: "desmondobiora@gmail.com",
    firstName: "Desmond",
    lastName: "Obiora",
    gender: "Male",
    status: "Approved",
  },
  {
    id: 15,
    email: "ayoolaawoniyi@gmail.com",
    firstName: "Ayoola",
    lastName: "Awoniyi",
    gender: "Female",
    status: "Approved",
  },
];
